#   Differential expression analysis with limma
#   Generated by GeoR, processes any normalized Geo Series!!

library(Biobase)
library(GEOquery)
library(limma)

# load series and platform data from GEO
# I like: Microglial, ARPE, ~Fibroblast, ~Hepatocyte, Keratinocyte, ~HSG


all_series <- data.frame(Cell = c("Thyroid", "Microglial", "AALEB", "ARPE", "Fibroblast", "Hepatocyte", "Keratinocyte", "HSG"),
                         Series = c("GSE5054", "GSE1432", "GSE77154", "GSE36331", "GSE67737", "GSE38147", "GSE12109", "GSE41291"),
                         Platform = c("GPL96", "GPL96", "GPL570", "GPL6244", "GPL10558", "GPL6244", "GPL571", "GPL6947"),
                         Selections = c("01XX01XX01XX", "XXXXXXXX1111XXXXXXXX0000", "0011XXXX", "00011XXXXXXXXXXXX", "000XXXXXXXXXXXXXXX111XXX", "00XXXXXX11", "1XX01XX01XX0",
                                        "XXXXXXXXXXXXXXXXXX000XXX111XXXXXXXXX"))

chosen <- "HSG" #cell type data to fetch
series <- toString(all_series[all_series$Cell == chosen, 2])
platform <- toString(all_series[all_series$Cell == chosen, 3])

gset <- getGEO(series, GSEMatrix =TRUE, AnnotGPL=TRUE)
if (length(gset) > 1) idx <- grep(platform, attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# make proper column names to match toptable 
fvarLabels(gset) <- make.names(fvarLabels(gset))

# group names for all samples
gsms <- toString(all_series[all_series$Cell == chosen, 4]) #string where 1 indicates test sample, 0 indicates control sample, and X indicates unnecessary.
sml <- c()
for (i in 1:nchar(gsms)) { sml[i] <- substr(gsms,i,i) }

# eliminate samples marked as "X"
sel <- which(sml != "X")
sml <- sml[sel]
gset <- gset[ ,sel]

# log2 transform
ex <- exprs(gset)
qx <- as.numeric(quantile(ex, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm=T))
LogC <- (qx[5] > 100) ||
  (qx[6]-qx[1] > 50 && qx[2] > 0) ||
  (qx[2] > 0 && qx[2] < 1 && qx[4] > 1 && qx[4] < 2)
if (LogC) { ex[which(ex <= 0)] <- NaN
exprs(gset) <- log2(ex) }

# set up the data and proceed with analysis
sml <- paste("G", sml, sep="")    # set group names
fl <- as.factor(sml)
gset$description <- fl
design <- model.matrix(~ description + 0, gset)
colnames(design) <- levels(fl)
fit <- lmFit(gset, design)
cont.matrix <- makeContrasts(G1-G0, levels=design)
fit2 <- contrasts.fit(fit, cont.matrix)
fit2 <- eBayes(fit2, 0.01)
tT <- topTable(fit2, adjust="fdr", sort.by="B", number=Inf)

tT <- subset(tT, select=c("ID","adj.P.Val","P.Value","t","B","logFC","Gene.symbol","Gene.title", "GO.Function.ID", "GO.Process.ID", "GO.Component.ID"))

of_interest <- as.integer(nrow(tT[tT$P.Value <= 0.05 & abs(tT$logFC) >= 1, ]))
of_interest_nop <- as.integer(nrow(tT[abs(tT$logFC) >= 1, ]))

supp <- as.integer(nrow(tT[tT$P.Value <= 0.05 & tT$logFC <= -1, ]))
act <- as.integer(nrow(tT[tT$P.Value <= 0.05 & tT$logFC >= 1, ]))

print(c(of_interest))
print(c(supp, act))
hist(tT$P.Value)

#sort by p value and log fold change, remove duplicates
tT.sort <- tT[order(-abs(tT$logFC), tT$P.Value),]
tT.sort <- tT.sort[!duplicated(tT.sort$Gene.symbol),]



#make final and save
final <- tab2.sort[,c(10, 11, 12, 13, 6, 2, 8, 7, 1, 3, 4, 5, 14, 15, 16, 17, 18, 19)]
write.csv(final, file = "~/Desktop/MacMicking Lab/IFN_microarray/Processed Data/microglialf.csv")


write.table(tT, file=stdout(), row.names=F, sep=",")


